---

- name: Adding Elastic PGP key 
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Installing apt transport https
  apt:
    name: apt-transport-https
    state: present

- name: Adding filebeat 7.x repository
  apt_repository: 
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present 
    filename: elastic-7.x
#    update_cache: yes

- name: Installing filebeat from apt repository
  apt: 
    name: filebeat
    state: present
    update_cache: yes

- name: Copying config file 
  template: 
    src: filebeat.j2
    dest: /etc/filebeat/filebeat.yml

- name: Reloading systemd daemon
  systemd: 
    daemon_reload: yes

- name: Enabling filebeat.service
  systemd:
    name: filebeat.service
    enabled: yes

- name: Start filebeat.service
  systemd: 
    name: filebeat.service
    state: restarted
  become: true
