---

- name: Adding Elastic PGP key 
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Installing apt transport https
  apt:
    name: apt-transport-https
    state: present

- name: Adding packetbeat 7.x repository
  apt_repository: 
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present 
    filename: elastic-7.x
#    update_cache: yes

- name: Installing packetbeat from apt repository
  apt: 
    name: packetbeat
    state: present
    update_cache: yes

- name: Copying config file 
  template: 
    src: packetbeat.j2
    dest: /etc/packetbeat/packetbeat.yml

- name: Reloading systemd daemon
  systemd: 
    daemon_reload: yes

- name: Enabling packetbeat.service
  systemd:
    name: packetbeat.service
    enabled: yes

- name: Start packetbeat.service
  systemd: 
    name: packetbeat.service
    state: restarted
  become: true
